version: '3.8'

services:
  # API service with Firebase
  app:
    build:
      context: .
      args:
        APP_ENV: ${APP_ENV:-development}
        FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID:-}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./logs:/app/logs
      - ./firebase-credentials.json:/app/firebase-credentials.json:ro
    env_file:
      - .env.${APP_ENV:-development}
    environment:
      - APP_ENV=${APP_ENV:-development}
      # Firebase
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-}
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
      - FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET:-}
      - FIREBASE_REGION=${FIREBASE_REGION:-us-central1}
      # LLM & Auth
      - LLM_API_KEY=${LLM_API_KEY:-dummy-key-for-development}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY:-}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY:-}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-supersecretkeythatshouldbechangedforproduction}

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: on-failure
